name: CD Pipeline - Development

on:
  push:
    branches: [ main ]

jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: '3.7'
      - name: Set up Node 14
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Set version to timestamp
        run: |
          VERSION=$(date +%s)
          PLACEHOLDER='__version__ = "0.0.1"'
          VERSION_FILE='huoguoml/__init__.py'
          grep "$PLACEHOLDER" "$VERSION_FILE"
          sed -i "s/$PLACEHOLDER/__version__ = \"${VERSION}\"/g" "$VERSION_FILE"
      - name: Change package name to huoguoml-dev
        run: |
          PKG_NAME=huoguoml-dev
          PLACEHOLDER='pkg_name = "huoguoml"'
          SETUP_PY='setup.py'
          grep "$PLACEHOLDER" "$SETUP_PY"
          sed -i "s/$PLACEHOLDER/pkg_name = \"${PKG_NAME}\"/g" "$SETUP_PY"
      - name: Install python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel twine
      - name: Build dashboard files
        working-directory: huoguoml/dashboard
        env:
          CI: false
        run: |
          yarn install
          yarn build
          mv build/index.html build/index.html.orig
      - name: Build and publish pip package
        env:
          TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        run: |
          python setup.py sdist bdist_wheel
          twine upload dist/*